name: Checks
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip install --upgrade pip
    - run: pip install "black<23" pylint==v3.0.0a3 mypy==v0.902 pydocstyle
    - run: black --diff --check $(git ls-files '*.py')
    - run: pydocstyle $(git ls-files '*.py')
      continue-on-error: true
    - run: mypy --strict $(git ls-files '*.py')
      continue-on-error: true
    - run: pylint $(git ls-files '*.py')
